package com.shop.entity.basic;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_admin.id
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_admin.login_name
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_admin.login_passward
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    private String loginPassward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_admin.nick_name
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_admin.create_time
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_admin.update_time
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_admin.is_delete
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_admin.id
     *
     * @return the value of mmfq_admin.id
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_admin.id
     *
     * @param id the value for mmfq_admin.id
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_admin.login_name
     *
     * @return the value of mmfq_admin.login_name
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_admin.login_name
     *
     * @param loginName the value for mmfq_admin.login_name
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_admin.login_passward
     *
     * @return the value of mmfq_admin.login_passward
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public String getLoginPassward() {
        return loginPassward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_admin.login_passward
     *
     * @param loginPassward the value for mmfq_admin.login_passward
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public void setLoginPassward(String loginPassward) {
        this.loginPassward = loginPassward == null ? null : loginPassward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_admin.nick_name
     *
     * @return the value of mmfq_admin.nick_name
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_admin.nick_name
     *
     * @param nickName the value for mmfq_admin.nick_name
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_admin.create_time
     *
     * @return the value of mmfq_admin.create_time
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_admin.create_time
     *
     * @param createTime the value for mmfq_admin.create_time
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_admin.update_time
     *
     * @return the value of mmfq_admin.update_time
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_admin.update_time
     *
     * @param updateTime the value for mmfq_admin.update_time
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_admin.is_delete
     *
     * @return the value of mmfq_admin.is_delete
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_admin.is_delete
     *
     * @param isDelete the value for mmfq_admin.is_delete
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}