package com.shop.entity.basic;

import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.id
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.category_id
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_sn
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_name
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_price
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_type
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_group_num_limit
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private Integer goodsGroupNumLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_group_time
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private Integer goodsGroupTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_sold_number
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private Integer goodsSoldNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_pic
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_show_pic
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsShowPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic1
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic2
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic3
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic4
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic5
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic6
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic7
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic8
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic9
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.goods_details_pic10
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private String goodsDetailsPic10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.is_delete
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.create_time
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods.update_time
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.id
     *
     * @return the value of mmfq_goods.id
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.id
     *
     * @param id the value for mmfq_goods.id
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.category_id
     *
     * @return the value of mmfq_goods.category_id
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.category_id
     *
     * @param categoryId the value for mmfq_goods.category_id
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_sn
     *
     * @return the value of mmfq_goods.goods_sn
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsSn() {
        return goodsSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_sn
     *
     * @param goodsSn the value for mmfq_goods.goods_sn
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsSn(String goodsSn) {
        this.goodsSn = goodsSn == null ? null : goodsSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_name
     *
     * @return the value of mmfq_goods.goods_name
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_name
     *
     * @param goodsName the value for mmfq_goods.goods_name
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_price
     *
     * @return the value of mmfq_goods.goods_price
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_price
     *
     * @param goodsPrice the value for mmfq_goods.goods_price
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_type
     *
     * @return the value of mmfq_goods.goods_type
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_type
     *
     * @param goodsType the value for mmfq_goods.goods_type
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_group_num_limit
     *
     * @return the value of mmfq_goods.goods_group_num_limit
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Integer getGoodsGroupNumLimit() {
        return goodsGroupNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_group_num_limit
     *
     * @param goodsGroupNumLimit the value for mmfq_goods.goods_group_num_limit
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsGroupNumLimit(Integer goodsGroupNumLimit) {
        this.goodsGroupNumLimit = goodsGroupNumLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_group_time
     *
     * @return the value of mmfq_goods.goods_group_time
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Integer getGoodsGroupTime() {
        return goodsGroupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_group_time
     *
     * @param goodsGroupTime the value for mmfq_goods.goods_group_time
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsGroupTime(Integer goodsGroupTime) {
        this.goodsGroupTime = goodsGroupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_sold_number
     *
     * @return the value of mmfq_goods.goods_sold_number
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Integer getGoodsSoldNumber() {
        return goodsSoldNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_sold_number
     *
     * @param goodsSoldNumber the value for mmfq_goods.goods_sold_number
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsSoldNumber(Integer goodsSoldNumber) {
        this.goodsSoldNumber = goodsSoldNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_pic
     *
     * @return the value of mmfq_goods.goods_pic
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_pic
     *
     * @param goodsPic the value for mmfq_goods.goods_pic
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic == null ? null : goodsPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_show_pic
     *
     * @return the value of mmfq_goods.goods_details_show_pic
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsShowPic() {
        return goodsDetailsShowPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_show_pic
     *
     * @param goodsDetailsShowPic the value for mmfq_goods.goods_details_show_pic
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsShowPic(String goodsDetailsShowPic) {
        this.goodsDetailsShowPic = goodsDetailsShowPic == null ? null : goodsDetailsShowPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic1
     *
     * @return the value of mmfq_goods.goods_details_pic1
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic1() {
        return goodsDetailsPic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic1
     *
     * @param goodsDetailsPic1 the value for mmfq_goods.goods_details_pic1
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic1(String goodsDetailsPic1) {
        this.goodsDetailsPic1 = goodsDetailsPic1 == null ? null : goodsDetailsPic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic2
     *
     * @return the value of mmfq_goods.goods_details_pic2
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic2() {
        return goodsDetailsPic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic2
     *
     * @param goodsDetailsPic2 the value for mmfq_goods.goods_details_pic2
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic2(String goodsDetailsPic2) {
        this.goodsDetailsPic2 = goodsDetailsPic2 == null ? null : goodsDetailsPic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic3
     *
     * @return the value of mmfq_goods.goods_details_pic3
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic3() {
        return goodsDetailsPic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic3
     *
     * @param goodsDetailsPic3 the value for mmfq_goods.goods_details_pic3
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic3(String goodsDetailsPic3) {
        this.goodsDetailsPic3 = goodsDetailsPic3 == null ? null : goodsDetailsPic3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic4
     *
     * @return the value of mmfq_goods.goods_details_pic4
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic4() {
        return goodsDetailsPic4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic4
     *
     * @param goodsDetailsPic4 the value for mmfq_goods.goods_details_pic4
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic4(String goodsDetailsPic4) {
        this.goodsDetailsPic4 = goodsDetailsPic4 == null ? null : goodsDetailsPic4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic5
     *
     * @return the value of mmfq_goods.goods_details_pic5
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic5() {
        return goodsDetailsPic5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic5
     *
     * @param goodsDetailsPic5 the value for mmfq_goods.goods_details_pic5
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic5(String goodsDetailsPic5) {
        this.goodsDetailsPic5 = goodsDetailsPic5 == null ? null : goodsDetailsPic5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic6
     *
     * @return the value of mmfq_goods.goods_details_pic6
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic6() {
        return goodsDetailsPic6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic6
     *
     * @param goodsDetailsPic6 the value for mmfq_goods.goods_details_pic6
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic6(String goodsDetailsPic6) {
        this.goodsDetailsPic6 = goodsDetailsPic6 == null ? null : goodsDetailsPic6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic7
     *
     * @return the value of mmfq_goods.goods_details_pic7
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic7() {
        return goodsDetailsPic7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic7
     *
     * @param goodsDetailsPic7 the value for mmfq_goods.goods_details_pic7
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic7(String goodsDetailsPic7) {
        this.goodsDetailsPic7 = goodsDetailsPic7 == null ? null : goodsDetailsPic7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic8
     *
     * @return the value of mmfq_goods.goods_details_pic8
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic8() {
        return goodsDetailsPic8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic8
     *
     * @param goodsDetailsPic8 the value for mmfq_goods.goods_details_pic8
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic8(String goodsDetailsPic8) {
        this.goodsDetailsPic8 = goodsDetailsPic8 == null ? null : goodsDetailsPic8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic9
     *
     * @return the value of mmfq_goods.goods_details_pic9
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic9() {
        return goodsDetailsPic9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic9
     *
     * @param goodsDetailsPic9 the value for mmfq_goods.goods_details_pic9
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic9(String goodsDetailsPic9) {
        this.goodsDetailsPic9 = goodsDetailsPic9 == null ? null : goodsDetailsPic9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.goods_details_pic10
     *
     * @return the value of mmfq_goods.goods_details_pic10
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getGoodsDetailsPic10() {
        return goodsDetailsPic10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.goods_details_pic10
     *
     * @param goodsDetailsPic10 the value for mmfq_goods.goods_details_pic10
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setGoodsDetailsPic10(String goodsDetailsPic10) {
        this.goodsDetailsPic10 = goodsDetailsPic10 == null ? null : goodsDetailsPic10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.is_delete
     *
     * @return the value of mmfq_goods.is_delete
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.is_delete
     *
     * @param isDelete the value for mmfq_goods.is_delete
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.create_time
     *
     * @return the value of mmfq_goods.create_time
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.create_time
     *
     * @param createTime the value for mmfq_goods.create_time
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods.update_time
     *
     * @return the value of mmfq_goods.update_time
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods.update_time
     *
     * @param updateTime the value for mmfq_goods.update_time
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}