package com.shop.entity.basic;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public GoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Long value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Long value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Long value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Long value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Long> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Long> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Long value1, Long value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andGoodsSnIsNull() {
            addCriterion("goods_sn is null");
            return (Criteria) this;
        }

        public Criteria andGoodsSnIsNotNull() {
            addCriterion("goods_sn is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsSnEqualTo(String value) {
            addCriterion("goods_sn =", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotEqualTo(String value) {
            addCriterion("goods_sn <>", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnGreaterThan(String value) {
            addCriterion("goods_sn >", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnGreaterThanOrEqualTo(String value) {
            addCriterion("goods_sn >=", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnLessThan(String value) {
            addCriterion("goods_sn <", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnLessThanOrEqualTo(String value) {
            addCriterion("goods_sn <=", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnLike(String value) {
            addCriterion("goods_sn like", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotLike(String value) {
            addCriterion("goods_sn not like", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnIn(List<String> values) {
            addCriterion("goods_sn in", values, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotIn(List<String> values) {
            addCriterion("goods_sn not in", values, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnBetween(String value1, String value2) {
            addCriterion("goods_sn between", value1, value2, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotBetween(String value1, String value2) {
            addCriterion("goods_sn not between", value1, value2, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("goods_name is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("goods_name =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("goods_name <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("goods_name >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("goods_name >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("goods_name <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("goods_name <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("goods_name like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("goods_name not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("goods_name in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("goods_name not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("goods_name between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("goods_name not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNull() {
            addCriterion("goods_price is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNotNull() {
            addCriterion("goods_price is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceEqualTo(Double value) {
            addCriterion("goods_price =", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotEqualTo(Double value) {
            addCriterion("goods_price <>", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThan(Double value) {
            addCriterion("goods_price >", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("goods_price >=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThan(Double value) {
            addCriterion("goods_price <", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThanOrEqualTo(Double value) {
            addCriterion("goods_price <=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIn(List<Double> values) {
            addCriterion("goods_price in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotIn(List<Double> values) {
            addCriterion("goods_price not in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceBetween(Double value1, Double value2) {
            addCriterion("goods_price between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotBetween(Double value1, Double value2) {
            addCriterion("goods_price not between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIsNull() {
            addCriterion("goods_type is null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIsNotNull() {
            addCriterion("goods_type is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeEqualTo(String value) {
            addCriterion("goods_type =", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotEqualTo(String value) {
            addCriterion("goods_type <>", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeGreaterThan(String value) {
            addCriterion("goods_type >", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("goods_type >=", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLessThan(String value) {
            addCriterion("goods_type <", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLessThanOrEqualTo(String value) {
            addCriterion("goods_type <=", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeLike(String value) {
            addCriterion("goods_type like", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotLike(String value) {
            addCriterion("goods_type not like", value, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIn(List<String> values) {
            addCriterion("goods_type in", values, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotIn(List<String> values) {
            addCriterion("goods_type not in", values, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeBetween(String value1, String value2) {
            addCriterion("goods_type between", value1, value2, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeNotBetween(String value1, String value2) {
            addCriterion("goods_type not between", value1, value2, "goodsType");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitIsNull() {
            addCriterion("goods_group_num_limit is null");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitIsNotNull() {
            addCriterion("goods_group_num_limit is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitEqualTo(Integer value) {
            addCriterion("goods_group_num_limit =", value, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitNotEqualTo(Integer value) {
            addCriterion("goods_group_num_limit <>", value, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitGreaterThan(Integer value) {
            addCriterion("goods_group_num_limit >", value, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_group_num_limit >=", value, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitLessThan(Integer value) {
            addCriterion("goods_group_num_limit <", value, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitLessThanOrEqualTo(Integer value) {
            addCriterion("goods_group_num_limit <=", value, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitIn(List<Integer> values) {
            addCriterion("goods_group_num_limit in", values, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitNotIn(List<Integer> values) {
            addCriterion("goods_group_num_limit not in", values, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitBetween(Integer value1, Integer value2) {
            addCriterion("goods_group_num_limit between", value1, value2, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupNumLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_group_num_limit not between", value1, value2, "goodsGroupNumLimit");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeIsNull() {
            addCriterion("goods_group_time is null");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeIsNotNull() {
            addCriterion("goods_group_time is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeEqualTo(Integer value) {
            addCriterion("goods_group_time =", value, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeNotEqualTo(Integer value) {
            addCriterion("goods_group_time <>", value, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeGreaterThan(Integer value) {
            addCriterion("goods_group_time >", value, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_group_time >=", value, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeLessThan(Integer value) {
            addCriterion("goods_group_time <", value, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeLessThanOrEqualTo(Integer value) {
            addCriterion("goods_group_time <=", value, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeIn(List<Integer> values) {
            addCriterion("goods_group_time in", values, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeNotIn(List<Integer> values) {
            addCriterion("goods_group_time not in", values, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeBetween(Integer value1, Integer value2) {
            addCriterion("goods_group_time between", value1, value2, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsGroupTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_group_time not between", value1, value2, "goodsGroupTime");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberIsNull() {
            addCriterion("goods_sold_number is null");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberIsNotNull() {
            addCriterion("goods_sold_number is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberEqualTo(Integer value) {
            addCriterion("goods_sold_number =", value, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberNotEqualTo(Integer value) {
            addCriterion("goods_sold_number <>", value, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberGreaterThan(Integer value) {
            addCriterion("goods_sold_number >", value, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_sold_number >=", value, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberLessThan(Integer value) {
            addCriterion("goods_sold_number <", value, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberLessThanOrEqualTo(Integer value) {
            addCriterion("goods_sold_number <=", value, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberIn(List<Integer> values) {
            addCriterion("goods_sold_number in", values, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberNotIn(List<Integer> values) {
            addCriterion("goods_sold_number not in", values, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberBetween(Integer value1, Integer value2) {
            addCriterion("goods_sold_number between", value1, value2, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsSoldNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_sold_number not between", value1, value2, "goodsSoldNumber");
            return (Criteria) this;
        }

        public Criteria andGoodsPicIsNull() {
            addCriterion("goods_pic is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPicIsNotNull() {
            addCriterion("goods_pic is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPicEqualTo(String value) {
            addCriterion("goods_pic =", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicNotEqualTo(String value) {
            addCriterion("goods_pic <>", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicGreaterThan(String value) {
            addCriterion("goods_pic >", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicGreaterThanOrEqualTo(String value) {
            addCriterion("goods_pic >=", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicLessThan(String value) {
            addCriterion("goods_pic <", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicLessThanOrEqualTo(String value) {
            addCriterion("goods_pic <=", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicLike(String value) {
            addCriterion("goods_pic like", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicNotLike(String value) {
            addCriterion("goods_pic not like", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicIn(List<String> values) {
            addCriterion("goods_pic in", values, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicNotIn(List<String> values) {
            addCriterion("goods_pic not in", values, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicBetween(String value1, String value2) {
            addCriterion("goods_pic between", value1, value2, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicNotBetween(String value1, String value2) {
            addCriterion("goods_pic not between", value1, value2, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicIsNull() {
            addCriterion("goods_details_show_pic is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicIsNotNull() {
            addCriterion("goods_details_show_pic is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicEqualTo(String value) {
            addCriterion("goods_details_show_pic =", value, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicNotEqualTo(String value) {
            addCriterion("goods_details_show_pic <>", value, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicGreaterThan(String value) {
            addCriterion("goods_details_show_pic >", value, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicGreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_show_pic >=", value, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicLessThan(String value) {
            addCriterion("goods_details_show_pic <", value, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicLessThanOrEqualTo(String value) {
            addCriterion("goods_details_show_pic <=", value, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicLike(String value) {
            addCriterion("goods_details_show_pic like", value, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicNotLike(String value) {
            addCriterion("goods_details_show_pic not like", value, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicIn(List<String> values) {
            addCriterion("goods_details_show_pic in", values, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicNotIn(List<String> values) {
            addCriterion("goods_details_show_pic not in", values, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicBetween(String value1, String value2) {
            addCriterion("goods_details_show_pic between", value1, value2, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsShowPicNotBetween(String value1, String value2) {
            addCriterion("goods_details_show_pic not between", value1, value2, "goodsDetailsShowPic");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1IsNull() {
            addCriterion("goods_details_pic1 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1IsNotNull() {
            addCriterion("goods_details_pic1 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1EqualTo(String value) {
            addCriterion("goods_details_pic1 =", value, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1NotEqualTo(String value) {
            addCriterion("goods_details_pic1 <>", value, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1GreaterThan(String value) {
            addCriterion("goods_details_pic1 >", value, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic1 >=", value, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1LessThan(String value) {
            addCriterion("goods_details_pic1 <", value, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic1 <=", value, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1Like(String value) {
            addCriterion("goods_details_pic1 like", value, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1NotLike(String value) {
            addCriterion("goods_details_pic1 not like", value, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1In(List<String> values) {
            addCriterion("goods_details_pic1 in", values, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1NotIn(List<String> values) {
            addCriterion("goods_details_pic1 not in", values, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1Between(String value1, String value2) {
            addCriterion("goods_details_pic1 between", value1, value2, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic1NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic1 not between", value1, value2, "goodsDetailsPic1");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2IsNull() {
            addCriterion("goods_details_pic2 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2IsNotNull() {
            addCriterion("goods_details_pic2 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2EqualTo(String value) {
            addCriterion("goods_details_pic2 =", value, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2NotEqualTo(String value) {
            addCriterion("goods_details_pic2 <>", value, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2GreaterThan(String value) {
            addCriterion("goods_details_pic2 >", value, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic2 >=", value, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2LessThan(String value) {
            addCriterion("goods_details_pic2 <", value, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic2 <=", value, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2Like(String value) {
            addCriterion("goods_details_pic2 like", value, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2NotLike(String value) {
            addCriterion("goods_details_pic2 not like", value, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2In(List<String> values) {
            addCriterion("goods_details_pic2 in", values, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2NotIn(List<String> values) {
            addCriterion("goods_details_pic2 not in", values, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2Between(String value1, String value2) {
            addCriterion("goods_details_pic2 between", value1, value2, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic2NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic2 not between", value1, value2, "goodsDetailsPic2");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3IsNull() {
            addCriterion("goods_details_pic3 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3IsNotNull() {
            addCriterion("goods_details_pic3 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3EqualTo(String value) {
            addCriterion("goods_details_pic3 =", value, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3NotEqualTo(String value) {
            addCriterion("goods_details_pic3 <>", value, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3GreaterThan(String value) {
            addCriterion("goods_details_pic3 >", value, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic3 >=", value, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3LessThan(String value) {
            addCriterion("goods_details_pic3 <", value, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic3 <=", value, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3Like(String value) {
            addCriterion("goods_details_pic3 like", value, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3NotLike(String value) {
            addCriterion("goods_details_pic3 not like", value, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3In(List<String> values) {
            addCriterion("goods_details_pic3 in", values, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3NotIn(List<String> values) {
            addCriterion("goods_details_pic3 not in", values, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3Between(String value1, String value2) {
            addCriterion("goods_details_pic3 between", value1, value2, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic3NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic3 not between", value1, value2, "goodsDetailsPic3");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4IsNull() {
            addCriterion("goods_details_pic4 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4IsNotNull() {
            addCriterion("goods_details_pic4 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4EqualTo(String value) {
            addCriterion("goods_details_pic4 =", value, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4NotEqualTo(String value) {
            addCriterion("goods_details_pic4 <>", value, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4GreaterThan(String value) {
            addCriterion("goods_details_pic4 >", value, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic4 >=", value, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4LessThan(String value) {
            addCriterion("goods_details_pic4 <", value, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic4 <=", value, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4Like(String value) {
            addCriterion("goods_details_pic4 like", value, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4NotLike(String value) {
            addCriterion("goods_details_pic4 not like", value, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4In(List<String> values) {
            addCriterion("goods_details_pic4 in", values, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4NotIn(List<String> values) {
            addCriterion("goods_details_pic4 not in", values, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4Between(String value1, String value2) {
            addCriterion("goods_details_pic4 between", value1, value2, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic4NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic4 not between", value1, value2, "goodsDetailsPic4");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5IsNull() {
            addCriterion("goods_details_pic5 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5IsNotNull() {
            addCriterion("goods_details_pic5 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5EqualTo(String value) {
            addCriterion("goods_details_pic5 =", value, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5NotEqualTo(String value) {
            addCriterion("goods_details_pic5 <>", value, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5GreaterThan(String value) {
            addCriterion("goods_details_pic5 >", value, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic5 >=", value, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5LessThan(String value) {
            addCriterion("goods_details_pic5 <", value, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic5 <=", value, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5Like(String value) {
            addCriterion("goods_details_pic5 like", value, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5NotLike(String value) {
            addCriterion("goods_details_pic5 not like", value, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5In(List<String> values) {
            addCriterion("goods_details_pic5 in", values, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5NotIn(List<String> values) {
            addCriterion("goods_details_pic5 not in", values, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5Between(String value1, String value2) {
            addCriterion("goods_details_pic5 between", value1, value2, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic5NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic5 not between", value1, value2, "goodsDetailsPic5");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6IsNull() {
            addCriterion("goods_details_pic6 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6IsNotNull() {
            addCriterion("goods_details_pic6 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6EqualTo(String value) {
            addCriterion("goods_details_pic6 =", value, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6NotEqualTo(String value) {
            addCriterion("goods_details_pic6 <>", value, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6GreaterThan(String value) {
            addCriterion("goods_details_pic6 >", value, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic6 >=", value, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6LessThan(String value) {
            addCriterion("goods_details_pic6 <", value, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic6 <=", value, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6Like(String value) {
            addCriterion("goods_details_pic6 like", value, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6NotLike(String value) {
            addCriterion("goods_details_pic6 not like", value, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6In(List<String> values) {
            addCriterion("goods_details_pic6 in", values, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6NotIn(List<String> values) {
            addCriterion("goods_details_pic6 not in", values, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6Between(String value1, String value2) {
            addCriterion("goods_details_pic6 between", value1, value2, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic6NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic6 not between", value1, value2, "goodsDetailsPic6");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7IsNull() {
            addCriterion("goods_details_pic7 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7IsNotNull() {
            addCriterion("goods_details_pic7 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7EqualTo(String value) {
            addCriterion("goods_details_pic7 =", value, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7NotEqualTo(String value) {
            addCriterion("goods_details_pic7 <>", value, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7GreaterThan(String value) {
            addCriterion("goods_details_pic7 >", value, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic7 >=", value, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7LessThan(String value) {
            addCriterion("goods_details_pic7 <", value, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic7 <=", value, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7Like(String value) {
            addCriterion("goods_details_pic7 like", value, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7NotLike(String value) {
            addCriterion("goods_details_pic7 not like", value, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7In(List<String> values) {
            addCriterion("goods_details_pic7 in", values, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7NotIn(List<String> values) {
            addCriterion("goods_details_pic7 not in", values, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7Between(String value1, String value2) {
            addCriterion("goods_details_pic7 between", value1, value2, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic7NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic7 not between", value1, value2, "goodsDetailsPic7");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8IsNull() {
            addCriterion("goods_details_pic8 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8IsNotNull() {
            addCriterion("goods_details_pic8 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8EqualTo(String value) {
            addCriterion("goods_details_pic8 =", value, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8NotEqualTo(String value) {
            addCriterion("goods_details_pic8 <>", value, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8GreaterThan(String value) {
            addCriterion("goods_details_pic8 >", value, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic8 >=", value, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8LessThan(String value) {
            addCriterion("goods_details_pic8 <", value, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic8 <=", value, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8Like(String value) {
            addCriterion("goods_details_pic8 like", value, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8NotLike(String value) {
            addCriterion("goods_details_pic8 not like", value, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8In(List<String> values) {
            addCriterion("goods_details_pic8 in", values, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8NotIn(List<String> values) {
            addCriterion("goods_details_pic8 not in", values, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8Between(String value1, String value2) {
            addCriterion("goods_details_pic8 between", value1, value2, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic8NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic8 not between", value1, value2, "goodsDetailsPic8");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9IsNull() {
            addCriterion("goods_details_pic9 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9IsNotNull() {
            addCriterion("goods_details_pic9 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9EqualTo(String value) {
            addCriterion("goods_details_pic9 =", value, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9NotEqualTo(String value) {
            addCriterion("goods_details_pic9 <>", value, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9GreaterThan(String value) {
            addCriterion("goods_details_pic9 >", value, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic9 >=", value, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9LessThan(String value) {
            addCriterion("goods_details_pic9 <", value, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic9 <=", value, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9Like(String value) {
            addCriterion("goods_details_pic9 like", value, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9NotLike(String value) {
            addCriterion("goods_details_pic9 not like", value, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9In(List<String> values) {
            addCriterion("goods_details_pic9 in", values, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9NotIn(List<String> values) {
            addCriterion("goods_details_pic9 not in", values, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9Between(String value1, String value2) {
            addCriterion("goods_details_pic9 between", value1, value2, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic9NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic9 not between", value1, value2, "goodsDetailsPic9");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10IsNull() {
            addCriterion("goods_details_pic10 is null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10IsNotNull() {
            addCriterion("goods_details_pic10 is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10EqualTo(String value) {
            addCriterion("goods_details_pic10 =", value, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10NotEqualTo(String value) {
            addCriterion("goods_details_pic10 <>", value, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10GreaterThan(String value) {
            addCriterion("goods_details_pic10 >", value, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10GreaterThanOrEqualTo(String value) {
            addCriterion("goods_details_pic10 >=", value, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10LessThan(String value) {
            addCriterion("goods_details_pic10 <", value, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10LessThanOrEqualTo(String value) {
            addCriterion("goods_details_pic10 <=", value, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10Like(String value) {
            addCriterion("goods_details_pic10 like", value, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10NotLike(String value) {
            addCriterion("goods_details_pic10 not like", value, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10In(List<String> values) {
            addCriterion("goods_details_pic10 in", values, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10NotIn(List<String> values) {
            addCriterion("goods_details_pic10 not in", values, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10Between(String value1, String value2) {
            addCriterion("goods_details_pic10 between", value1, value2, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andGoodsDetailsPic10NotBetween(String value1, String value2) {
            addCriterion("goods_details_pic10 not between", value1, value2, "goodsDetailsPic10");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Boolean value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Boolean value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Boolean value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Boolean value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Boolean> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Boolean> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mmfq_goods
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 13 12:21:35 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}