package com.shop.entity.basic;

import java.util.Date;

public class GoodsCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods_category.id
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods_category.category_name
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods_category.is_delete
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods_category.create_time
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_goods_category.update_time
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods_category.id
     *
     * @return the value of mmfq_goods_category.id
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods_category.id
     *
     * @param id the value for mmfq_goods_category.id
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods_category.category_name
     *
     * @return the value of mmfq_goods_category.category_name
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods_category.category_name
     *
     * @param categoryName the value for mmfq_goods_category.category_name
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods_category.is_delete
     *
     * @return the value of mmfq_goods_category.is_delete
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods_category.is_delete
     *
     * @param isDelete the value for mmfq_goods_category.is_delete
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods_category.create_time
     *
     * @return the value of mmfq_goods_category.create_time
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods_category.create_time
     *
     * @param createTime the value for mmfq_goods_category.create_time
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_goods_category.update_time
     *
     * @return the value of mmfq_goods_category.update_time
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_goods_category.update_time
     *
     * @param updateTime the value for mmfq_goods_category.update_time
     *
     * @mbggenerated Tue Nov 29 11:21:34 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}