package com.shop.entity.basic;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TeamOrderRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public TeamOrderRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnIsNull() {
            addCriterion("team_group_sn is null");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnIsNotNull() {
            addCriterion("team_group_sn is not null");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnEqualTo(String value) {
            addCriterion("team_group_sn =", value, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnNotEqualTo(String value) {
            addCriterion("team_group_sn <>", value, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnGreaterThan(String value) {
            addCriterion("team_group_sn >", value, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnGreaterThanOrEqualTo(String value) {
            addCriterion("team_group_sn >=", value, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnLessThan(String value) {
            addCriterion("team_group_sn <", value, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnLessThanOrEqualTo(String value) {
            addCriterion("team_group_sn <=", value, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnLike(String value) {
            addCriterion("team_group_sn like", value, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnNotLike(String value) {
            addCriterion("team_group_sn not like", value, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnIn(List<String> values) {
            addCriterion("team_group_sn in", values, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnNotIn(List<String> values) {
            addCriterion("team_group_sn not in", values, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnBetween(String value1, String value2) {
            addCriterion("team_group_sn between", value1, value2, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andTeamGroupSnNotBetween(String value1, String value2) {
            addCriterion("team_group_sn not between", value1, value2, "teamGroupSn");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Long value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Long value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Long value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Long value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Long value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Long> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Long> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Long value1, Long value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Long value1, Long value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("goods_name is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("goods_name =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("goods_name <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("goods_name >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("goods_name >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("goods_name <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("goods_name <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("goods_name like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("goods_name not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("goods_name in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("goods_name not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("goods_name between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("goods_name not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNull() {
            addCriterion("goods_price is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNotNull() {
            addCriterion("goods_price is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceEqualTo(Double value) {
            addCriterion("goods_price =", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotEqualTo(Double value) {
            addCriterion("goods_price <>", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThan(Double value) {
            addCriterion("goods_price >", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("goods_price >=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThan(Double value) {
            addCriterion("goods_price <", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThanOrEqualTo(Double value) {
            addCriterion("goods_price <=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIn(List<Double> values) {
            addCriterion("goods_price in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotIn(List<Double> values) {
            addCriterion("goods_price not in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceBetween(Double value1, Double value2) {
            addCriterion("goods_price between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotBetween(Double value1, Double value2) {
            addCriterion("goods_price not between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPicIsNull() {
            addCriterion("goods_pic is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPicIsNotNull() {
            addCriterion("goods_pic is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPicEqualTo(String value) {
            addCriterion("goods_pic =", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicNotEqualTo(String value) {
            addCriterion("goods_pic <>", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicGreaterThan(String value) {
            addCriterion("goods_pic >", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicGreaterThanOrEqualTo(String value) {
            addCriterion("goods_pic >=", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicLessThan(String value) {
            addCriterion("goods_pic <", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicLessThanOrEqualTo(String value) {
            addCriterion("goods_pic <=", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicLike(String value) {
            addCriterion("goods_pic like", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicNotLike(String value) {
            addCriterion("goods_pic not like", value, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicIn(List<String> values) {
            addCriterion("goods_pic in", values, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicNotIn(List<String> values) {
            addCriterion("goods_pic not in", values, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicBetween(String value1, String value2) {
            addCriterion("goods_pic between", value1, value2, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andGoodsPicNotBetween(String value1, String value2) {
            addCriterion("goods_pic not between", value1, value2, "goodsPic");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumIsNull() {
            addCriterion("total_person_num is null");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumIsNotNull() {
            addCriterion("total_person_num is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumEqualTo(Integer value) {
            addCriterion("total_person_num =", value, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumNotEqualTo(Integer value) {
            addCriterion("total_person_num <>", value, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumGreaterThan(Integer value) {
            addCriterion("total_person_num >", value, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_person_num >=", value, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumLessThan(Integer value) {
            addCriterion("total_person_num <", value, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumLessThanOrEqualTo(Integer value) {
            addCriterion("total_person_num <=", value, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumIn(List<Integer> values) {
            addCriterion("total_person_num in", values, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumNotIn(List<Integer> values) {
            addCriterion("total_person_num not in", values, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumBetween(Integer value1, Integer value2) {
            addCriterion("total_person_num between", value1, value2, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andTotalPersonNumNotBetween(Integer value1, Integer value2) {
            addCriterion("total_person_num not between", value1, value2, "totalPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumIsNull() {
            addCriterion("buy_person_num is null");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumIsNotNull() {
            addCriterion("buy_person_num is not null");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumEqualTo(Integer value) {
            addCriterion("buy_person_num =", value, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumNotEqualTo(Integer value) {
            addCriterion("buy_person_num <>", value, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumGreaterThan(Integer value) {
            addCriterion("buy_person_num >", value, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("buy_person_num >=", value, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumLessThan(Integer value) {
            addCriterion("buy_person_num <", value, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumLessThanOrEqualTo(Integer value) {
            addCriterion("buy_person_num <=", value, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumIn(List<Integer> values) {
            addCriterion("buy_person_num in", values, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumNotIn(List<Integer> values) {
            addCriterion("buy_person_num not in", values, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumBetween(Integer value1, Integer value2) {
            addCriterion("buy_person_num between", value1, value2, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andBuyPersonNumNotBetween(Integer value1, Integer value2) {
            addCriterion("buy_person_num not between", value1, value2, "buyPersonNum");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andIsFinishedIsNull() {
            addCriterion("is_finished is null");
            return (Criteria) this;
        }

        public Criteria andIsFinishedIsNotNull() {
            addCriterion("is_finished is not null");
            return (Criteria) this;
        }

        public Criteria andIsFinishedEqualTo(Integer value) {
            addCriterion("is_finished =", value, "isFinished");
            return (Criteria) this;
        }

        public Criteria andIsFinishedNotEqualTo(Integer value) {
            addCriterion("is_finished <>", value, "isFinished");
            return (Criteria) this;
        }

        public Criteria andIsFinishedGreaterThan(Integer value) {
            addCriterion("is_finished >", value, "isFinished");
            return (Criteria) this;
        }

        public Criteria andIsFinishedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_finished >=", value, "isFinished");
            return (Criteria) this;
        }

        public Criteria andIsFinishedLessThan(Integer value) {
            addCriterion("is_finished <", value, "isFinished");
            return (Criteria) this;
        }

        public Criteria andIsFinishedLessThanOrEqualTo(Integer value) {
            addCriterion("is_finished <=", value, "isFinished");
            return (Criteria) this;
        }

        public Criteria andIsFinishedIn(List<Integer> values) {
            addCriterion("is_finished in", values, "isFinished");
            return (Criteria) this;
        }

        public Criteria andIsFinishedNotIn(List<Integer> values) {
            addCriterion("is_finished not in", values, "isFinished");
            return (Criteria) this;
        }

        public Criteria andIsFinishedBetween(Integer value1, Integer value2) {
            addCriterion("is_finished between", value1, value2, "isFinished");
            return (Criteria) this;
        }

        public Criteria andIsFinishedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_finished not between", value1, value2, "isFinished");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeIsNull() {
            addCriterion("finished_time is null");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeIsNotNull() {
            addCriterion("finished_time is not null");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeEqualTo(Date value) {
            addCriterion("finished_time =", value, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeNotEqualTo(Date value) {
            addCriterion("finished_time <>", value, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeGreaterThan(Date value) {
            addCriterion("finished_time >", value, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("finished_time >=", value, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeLessThan(Date value) {
            addCriterion("finished_time <", value, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeLessThanOrEqualTo(Date value) {
            addCriterion("finished_time <=", value, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeIn(List<Date> values) {
            addCriterion("finished_time in", values, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeNotIn(List<Date> values) {
            addCriterion("finished_time not in", values, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeBetween(Date value1, Date value2) {
            addCriterion("finished_time between", value1, value2, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andFinishedTimeNotBetween(Date value1, Date value2) {
            addCriterion("finished_time not between", value1, value2, "finishedTime");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdIsNull() {
            addCriterion("team_leader_id is null");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdIsNotNull() {
            addCriterion("team_leader_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdEqualTo(Long value) {
            addCriterion("team_leader_id =", value, "teamLeaderId");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdNotEqualTo(Long value) {
            addCriterion("team_leader_id <>", value, "teamLeaderId");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdGreaterThan(Long value) {
            addCriterion("team_leader_id >", value, "teamLeaderId");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("team_leader_id >=", value, "teamLeaderId");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdLessThan(Long value) {
            addCriterion("team_leader_id <", value, "teamLeaderId");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdLessThanOrEqualTo(Long value) {
            addCriterion("team_leader_id <=", value, "teamLeaderId");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdIn(List<Long> values) {
            addCriterion("team_leader_id in", values, "teamLeaderId");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdNotIn(List<Long> values) {
            addCriterion("team_leader_id not in", values, "teamLeaderId");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdBetween(Long value1, Long value2) {
            addCriterion("team_leader_id between", value1, value2, "teamLeaderId");
            return (Criteria) this;
        }

        public Criteria andTeamLeaderIdNotBetween(Long value1, Long value2) {
            addCriterion("team_leader_id not between", value1, value2, "teamLeaderId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 13 14:25:36 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}