package com.shop.entity.basic;

import java.util.Date;

public class TeamOrderRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.team_group_sn
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private String teamGroupSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.goods_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.goods_name
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.goods_price
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.goods_pic
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private String goodsPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.total_person_num
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Integer totalPersonNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.buy_person_num
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Integer buyPersonNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.create_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.end_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.is_finished
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Integer isFinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.finished_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Date finishedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_order_record.team_leader_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Long teamLeaderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.id
     *
     * @return the value of mmfq_team_order_record.id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.id
     *
     * @param id the value for mmfq_team_order_record.id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.team_group_sn
     *
     * @return the value of mmfq_team_order_record.team_group_sn
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public String getTeamGroupSn() {
        return teamGroupSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.team_group_sn
     *
     * @param teamGroupSn the value for mmfq_team_order_record.team_group_sn
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setTeamGroupSn(String teamGroupSn) {
        this.teamGroupSn = teamGroupSn == null ? null : teamGroupSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.goods_id
     *
     * @return the value of mmfq_team_order_record.goods_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.goods_id
     *
     * @param goodsId the value for mmfq_team_order_record.goods_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.goods_name
     *
     * @return the value of mmfq_team_order_record.goods_name
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.goods_name
     *
     * @param goodsName the value for mmfq_team_order_record.goods_name
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.goods_price
     *
     * @return the value of mmfq_team_order_record.goods_price
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.goods_price
     *
     * @param goodsPrice the value for mmfq_team_order_record.goods_price
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.goods_pic
     *
     * @return the value of mmfq_team_order_record.goods_pic
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.goods_pic
     *
     * @param goodsPic the value for mmfq_team_order_record.goods_pic
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic == null ? null : goodsPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.total_person_num
     *
     * @return the value of mmfq_team_order_record.total_person_num
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Integer getTotalPersonNum() {
        return totalPersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.total_person_num
     *
     * @param totalPersonNum the value for mmfq_team_order_record.total_person_num
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setTotalPersonNum(Integer totalPersonNum) {
        this.totalPersonNum = totalPersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.buy_person_num
     *
     * @return the value of mmfq_team_order_record.buy_person_num
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Integer getBuyPersonNum() {
        return buyPersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.buy_person_num
     *
     * @param buyPersonNum the value for mmfq_team_order_record.buy_person_num
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setBuyPersonNum(Integer buyPersonNum) {
        this.buyPersonNum = buyPersonNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.create_time
     *
     * @return the value of mmfq_team_order_record.create_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.create_time
     *
     * @param createTime the value for mmfq_team_order_record.create_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.end_time
     *
     * @return the value of mmfq_team_order_record.end_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.end_time
     *
     * @param endTime the value for mmfq_team_order_record.end_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.is_finished
     *
     * @return the value of mmfq_team_order_record.is_finished
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Integer getIsFinished() {
        return isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.is_finished
     *
     * @param isFinished the value for mmfq_team_order_record.is_finished
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setIsFinished(Integer isFinished) {
        this.isFinished = isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.finished_time
     *
     * @return the value of mmfq_team_order_record.finished_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Date getFinishedTime() {
        return finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.finished_time
     *
     * @param finishedTime the value for mmfq_team_order_record.finished_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setFinishedTime(Date finishedTime) {
        this.finishedTime = finishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_order_record.team_leader_id
     *
     * @return the value of mmfq_team_order_record.team_leader_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Long getTeamLeaderId() {
        return teamLeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_order_record.team_leader_id
     *
     * @param teamLeaderId the value for mmfq_team_order_record.team_leader_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setTeamLeaderId(Long teamLeaderId) {
        this.teamLeaderId = teamLeaderId;
    }
}