package com.shop.entity.basic;

import java.util.Date;

public class TeamMemberRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_member_record.id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_member_record.order_sn
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_member_record.user_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_member_record.team_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Long teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_member_record.receive_address
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private String receiveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_member_record.teanm_order_status
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Integer teanmOrderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_team_member_record.create_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_member_record.id
     *
     * @return the value of mmfq_team_member_record.id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_member_record.id
     *
     * @param id the value for mmfq_team_member_record.id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_member_record.order_sn
     *
     * @return the value of mmfq_team_member_record.order_sn
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_member_record.order_sn
     *
     * @param orderSn the value for mmfq_team_member_record.order_sn
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_member_record.user_id
     *
     * @return the value of mmfq_team_member_record.user_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_member_record.user_id
     *
     * @param userId the value for mmfq_team_member_record.user_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_member_record.team_id
     *
     * @return the value of mmfq_team_member_record.team_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_member_record.team_id
     *
     * @param teamId the value for mmfq_team_member_record.team_id
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_member_record.receive_address
     *
     * @return the value of mmfq_team_member_record.receive_address
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_member_record.receive_address
     *
     * @param receiveAddress the value for mmfq_team_member_record.receive_address
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress == null ? null : receiveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_member_record.teanm_order_status
     *
     * @return the value of mmfq_team_member_record.teanm_order_status
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Integer getTeanmOrderStatus() {
        return teanmOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_member_record.teanm_order_status
     *
     * @param teanmOrderStatus the value for mmfq_team_member_record.teanm_order_status
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setTeanmOrderStatus(Integer teanmOrderStatus) {
        this.teanmOrderStatus = teanmOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_team_member_record.create_time
     *
     * @return the value of mmfq_team_member_record.create_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_team_member_record.create_time
     *
     * @param createTime the value for mmfq_team_member_record.create_time
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}