package com.shop.entity.basic;

import java.util.Date;

public class UserReceiptAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_receipt_address.id
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_receipt_address.user_id
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_receipt_address.receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    private String receiptAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_receipt_address.receiver
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_receipt_address.telephone
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_receipt_address.is_default
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_receipt_address.create_time
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_receipt_address.update_time
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_receipt_address.id
     *
     * @return the value of mmfq_user_receipt_address.id
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_receipt_address.id
     *
     * @param id the value for mmfq_user_receipt_address.id
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_receipt_address.user_id
     *
     * @return the value of mmfq_user_receipt_address.user_id
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_receipt_address.user_id
     *
     * @param userId the value for mmfq_user_receipt_address.user_id
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_receipt_address.receipt_address
     *
     * @return the value of mmfq_user_receipt_address.receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public String getReceiptAddress() {
        return receiptAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_receipt_address.receipt_address
     *
     * @param receiptAddress the value for mmfq_user_receipt_address.receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public void setReceiptAddress(String receiptAddress) {
        this.receiptAddress = receiptAddress == null ? null : receiptAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_receipt_address.receiver
     *
     * @return the value of mmfq_user_receipt_address.receiver
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_receipt_address.receiver
     *
     * @param receiver the value for mmfq_user_receipt_address.receiver
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_receipt_address.telephone
     *
     * @return the value of mmfq_user_receipt_address.telephone
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_receipt_address.telephone
     *
     * @param telephone the value for mmfq_user_receipt_address.telephone
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_receipt_address.is_default
     *
     * @return the value of mmfq_user_receipt_address.is_default
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_receipt_address.is_default
     *
     * @param isDefault the value for mmfq_user_receipt_address.is_default
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_receipt_address.create_time
     *
     * @return the value of mmfq_user_receipt_address.create_time
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_receipt_address.create_time
     *
     * @param createTime the value for mmfq_user_receipt_address.create_time
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_receipt_address.update_time
     *
     * @return the value of mmfq_user_receipt_address.update_time
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_receipt_address.update_time
     *
     * @param updateTime the value for mmfq_user_receipt_address.update_time
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}