package com.shop.entity.basic;

import java.util.Date;

public class UserOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order.id
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order.receive_address
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    private String receiveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order.order_sn
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order.order_name
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    private String orderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order.order_price
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    private Double orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order.order_status
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order.user_id
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order.create_time
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order.update_time
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order.id
     *
     * @return the value of mmfq_user_order.id
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order.id
     *
     * @param id the value for mmfq_user_order.id
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order.receive_address
     *
     * @return the value of mmfq_user_order.receive_address
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order.receive_address
     *
     * @param receiveAddress the value for mmfq_user_order.receive_address
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress == null ? null : receiveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order.order_sn
     *
     * @return the value of mmfq_user_order.order_sn
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order.order_sn
     *
     * @param orderSn the value for mmfq_user_order.order_sn
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order.order_name
     *
     * @return the value of mmfq_user_order.order_name
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order.order_name
     *
     * @param orderName the value for mmfq_user_order.order_name
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName == null ? null : orderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order.order_price
     *
     * @return the value of mmfq_user_order.order_price
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public Double getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order.order_price
     *
     * @param orderPrice the value for mmfq_user_order.order_price
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public void setOrderPrice(Double orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order.order_status
     *
     * @return the value of mmfq_user_order.order_status
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order.order_status
     *
     * @param orderStatus the value for mmfq_user_order.order_status
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order.user_id
     *
     * @return the value of mmfq_user_order.user_id
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order.user_id
     *
     * @param userId the value for mmfq_user_order.user_id
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order.create_time
     *
     * @return the value of mmfq_user_order.create_time
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order.create_time
     *
     * @param createTime the value for mmfq_user_order.create_time
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order.update_time
     *
     * @return the value of mmfq_user_order.update_time
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order.update_time
     *
     * @param updateTime the value for mmfq_user_order.update_time
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}