package com.shop.entity.basic;

import java.util.Date;

public class UserOrderDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.id
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.user_id
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.goods_id
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.goods_name
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.goods_price
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private Double goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.goods_pic
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private String goodsPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.order_sn
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.num
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.create_time
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.update_time
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmfq_user_order_details.order_confirm_time
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    private Date orderConfirmTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.id
     *
     * @return the value of mmfq_user_order_details.id
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.id
     *
     * @param id the value for mmfq_user_order_details.id
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.user_id
     *
     * @return the value of mmfq_user_order_details.user_id
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.user_id
     *
     * @param userId the value for mmfq_user_order_details.user_id
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.goods_id
     *
     * @return the value of mmfq_user_order_details.goods_id
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.goods_id
     *
     * @param goodsId the value for mmfq_user_order_details.goods_id
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.goods_name
     *
     * @return the value of mmfq_user_order_details.goods_name
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.goods_name
     *
     * @param goodsName the value for mmfq_user_order_details.goods_name
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.goods_price
     *
     * @return the value of mmfq_user_order_details.goods_price
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.goods_price
     *
     * @param goodsPrice the value for mmfq_user_order_details.goods_price
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.goods_pic
     *
     * @return the value of mmfq_user_order_details.goods_pic
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.goods_pic
     *
     * @param goodsPic the value for mmfq_user_order_details.goods_pic
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic == null ? null : goodsPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.order_sn
     *
     * @return the value of mmfq_user_order_details.order_sn
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.order_sn
     *
     * @param orderSn the value for mmfq_user_order_details.order_sn
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.num
     *
     * @return the value of mmfq_user_order_details.num
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.num
     *
     * @param num the value for mmfq_user_order_details.num
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.create_time
     *
     * @return the value of mmfq_user_order_details.create_time
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.create_time
     *
     * @param createTime the value for mmfq_user_order_details.create_time
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.update_time
     *
     * @return the value of mmfq_user_order_details.update_time
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.update_time
     *
     * @param updateTime the value for mmfq_user_order_details.update_time
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmfq_user_order_details.order_confirm_time
     *
     * @return the value of mmfq_user_order_details.order_confirm_time
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public Date getOrderConfirmTime() {
        return orderConfirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmfq_user_order_details.order_confirm_time
     *
     * @param orderConfirmTime the value for mmfq_user_order_details.order_confirm_time
     *
     * @mbggenerated Wed Nov 30 16:31:51 CST 2016
     */
    public void setOrderConfirmTime(Date orderConfirmTime) {
        this.orderConfirmTime = orderConfirmTime;
    }
}