package com.shop.dao.basic;

import com.shop.entity.basic.Admin;
import com.shop.entity.basic.AdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    int countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    Admin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_admin
     *
     * @mbggenerated Tue Nov 29 16:56:21 CST 2016
     */
    int updateByPrimaryKey(Admin record);
}