package com.shop.dao.basic;

import com.shop.entity.basic.Goods;
import com.shop.entity.basic.GoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    int countByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    int deleteByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    List<Goods> selectByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    Goods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_goods
     *
     * @mbggenerated Tue Dec 13 12:21:35 CST 2016
     */
    int updateByPrimaryKey(Goods record);
}