package com.shop.dao.basic;

import com.shop.entity.basic.TeamMemberRecord;
import com.shop.entity.basic.TeamMemberRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamMemberRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int countByExample(TeamMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int deleteByExample(TeamMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int insert(TeamMemberRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int insertSelective(TeamMemberRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    List<TeamMemberRecord> selectByExample(TeamMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    TeamMemberRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") TeamMemberRecord record, @Param("example") TeamMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int updateByExample(@Param("record") TeamMemberRecord record, @Param("example") TeamMemberRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int updateByPrimaryKeySelective(TeamMemberRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_member_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int updateByPrimaryKey(TeamMemberRecord record);
}