package com.shop.dao.basic;

import com.shop.entity.basic.TeamOrderRecord;
import com.shop.entity.basic.TeamOrderRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamOrderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int countByExample(TeamOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int deleteByExample(TeamOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int insert(TeamOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int insertSelective(TeamOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    List<TeamOrderRecord> selectByExample(TeamOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    TeamOrderRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int updateByExampleSelective(@Param("record") TeamOrderRecord record, @Param("example") TeamOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int updateByExample(@Param("record") TeamOrderRecord record, @Param("example") TeamOrderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int updateByPrimaryKeySelective(TeamOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_team_order_record
     *
     * @mbggenerated Tue Dec 13 14:25:36 CST 2016
     */
    int updateByPrimaryKey(TeamOrderRecord record);
}