package com.shop.dao.basic;

import com.shop.entity.basic.UserOrder;
import com.shop.entity.basic.UserOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    int countByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    int deleteByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    int insert(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    int insertSelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    List<UserOrder> selectByExample(UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    UserOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserOrder record, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    int updateByExample(@Param("record") UserOrder record, @Param("example") UserOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    int updateByPrimaryKeySelective(UserOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_order
     *
     * @mbggenerated Wed Nov 30 16:30:34 CST 2016
     */
    int updateByPrimaryKey(UserOrder record);
}