package com.shop.dao.basic;

import com.shop.entity.basic.UserReceiptAddress;
import com.shop.entity.basic.UserReceiptAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserReceiptAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    int countByExample(UserReceiptAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    int deleteByExample(UserReceiptAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    int insert(UserReceiptAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    int insertSelective(UserReceiptAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    List<UserReceiptAddress> selectByExample(UserReceiptAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    UserReceiptAddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserReceiptAddress record, @Param("example") UserReceiptAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    int updateByExample(@Param("record") UserReceiptAddress record, @Param("example") UserReceiptAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    int updateByPrimaryKeySelective(UserReceiptAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmfq_user_receipt_address
     *
     * @mbggenerated Wed Nov 23 16:18:05 CST 2016
     */
    int updateByPrimaryKey(UserReceiptAddress record);
}